env:
    rcloneconfig: "ENCRYPTED[034e13cc8143fcabee611477a5e8352667cbc75adfca6d506a2b7cbf9d1f52a0d26c3dd3e7494b3d12567ddce64c9219]"
    tokentl: "ENCRYPTED[0a954bd80bc103bd3ecee6276c858326ce4b35ad5026aa148bed883404a599d12622d7e396a983f4d2ffeeb2cefb12a9]"
    idtl: "ENCRYPTED[8f901a1ed19c398a0e5a7631bb2948448881d43310c736d677dfa69f2034524b19bade1b1f7d8e8ba677e847d0341d0d]"
    MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
    MANIFEST_BRANCH: twrp-9.0
    DEVICE: vince
    DT_LINK: https://github.com/rxhulkxnt44/recovery_xiaomi_vince.git
    DT_PATH: device/xiaomi/vince
    TARGET: recoveryimage
    TZ: Asia/Kolkata

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 60m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Setting up build environment."
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "rk134"
       - git config --global user.email "rahul.kantrapally@gmail.com"
       - mkdir -p /tmp/ccache
       - rclone copy ccache:twrp/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Source is syncing! Please wait."
      - dir
      - cd /tmp && mkdir twrp
      - cd /tmp/twrp
      # DT
      - repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
      - repo sync -j8
      - git clone $DT_LINK --depth=1 --single-branch $DT_PATH
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
#      - ./collect.sh
      - chmod +x compile.sh && chmod +x zipper.sh
      - ./compile.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/*/*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/*/*.zip)"
      - rclone copy /tmp/rom/out/target/product/*/*.zip ccache:twrp -P
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/*/*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Download link https://retarded-sprout.axsp.workers.dev/vince/$(cd /tmp/rom/out/target/product/*/*.zip)"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Compressing ccache"
      - ./zipper.sh
      - cd /tmp
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz ccache:twrp -P
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
